/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTM4C_BSP_SET_SP_H
#define _MOCKTM4C_BSP_SET_SP_H

#include "unity.h"
#include "tm4c_bsp_set_sp.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocktm4c_bsp_set_sp_Init(void);
void Mocktm4c_bsp_set_sp_Destroy(void);
void Mocktm4c_bsp_set_sp_Verify(void);




#define set_sp_ExpectAndReturn(cmock_arg1, cmock_retval) TEST_FAIL_MESSAGE("set_sp requires _Expect (not AndReturn)");
#define set_sp_Expect(cmock_arg1) set_sp_CMockExpect(__LINE__, cmock_arg1)
void set_sp_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t* cmock_arg1);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
