/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktm4c_bsp.h"

static const char* CMockString_PLL_init = "PLL_init";
static const char* CMockString_SysTick_init = "SysTick_init";
static const char* CMockString_UART0_and_servos_init = "UART0_and_servos_init";
static const char* CMockString_cmock_arg1 = "cmock_arg1";
static const char* CMockString_delay_10ms = "delay_10ms";
static const char* CMockString_get_UART0_interrupt_data = "get_UART0_interrupt_data";
static const char* CMockString_set_PWM0_generator0_CMPA = "set_PWM0_generator0_CMPA";
static const char* CMockString_set_PWM0_generator1_CMPA = "set_PWM0_generator1_CMPA";

typedef struct _CMOCK_PLL_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_PLL_init_CALL_INSTANCE;

typedef struct _CMOCK_SysTick_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SysTick_init_CALL_INSTANCE;

typedef struct _CMOCK_delay_10ms_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned long Expected_cmock_arg1;

} CMOCK_delay_10ms_CALL_INSTANCE;

typedef struct _CMOCK_UART0_and_servos_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_UART0_and_servos_init_CALL_INSTANCE;

typedef struct _CMOCK_get_UART0_interrupt_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_get_UART0_interrupt_data_CALL_INSTANCE;

typedef struct _CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned short Expected_cmock_arg1;

} CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE;

typedef struct _CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned short Expected_cmock_arg1;

} CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE;

static struct Mocktm4c_bspInstance
{
  CMOCK_MEM_INDEX_TYPE PLL_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE SysTick_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE delay_10ms_CallInstance;
  CMOCK_MEM_INDEX_TYPE UART0_and_servos_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE get_UART0_interrupt_data_CallInstance;
  CMOCK_MEM_INDEX_TYPE set_PWM0_generator0_CMPA_CallInstance;
  CMOCK_MEM_INDEX_TYPE set_PWM0_generator1_CMPA_CallInstance;
} Mock;


void Mocktm4c_bsp_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.PLL_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PLL_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SysTick_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SysTick_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.delay_10ms_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_delay_10ms);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.UART0_and_servos_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART0_and_servos_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.get_UART0_interrupt_data_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_UART0_interrupt_data);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.set_PWM0_generator0_CMPA_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_PWM0_generator0_CMPA);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.set_PWM0_generator1_CMPA_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_PWM0_generator1_CMPA);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mocktm4c_bsp_Init(void)
{
  Mocktm4c_bsp_Destroy();
}

void Mocktm4c_bsp_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void PLL_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PLL_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PLL_init);
  cmock_call_instance = (CMOCK_PLL_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PLL_init_CallInstance);
  Mock.PLL_init_CallInstance = CMock_Guts_MemNext(Mock.PLL_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void PLL_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLL_init_CALL_INSTANCE));
  CMOCK_PLL_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLL_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLL_init_CallInstance = CMock_Guts_MemChain(Mock.PLL_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void SysTick_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SysTick_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SysTick_init);
  cmock_call_instance = (CMOCK_SysTick_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SysTick_init_CallInstance);
  Mock.SysTick_init_CallInstance = CMock_Guts_MemNext(Mock.SysTick_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SysTick_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SysTick_init_CALL_INSTANCE));
  CMOCK_SysTick_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_SysTick_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SysTick_init_CallInstance = CMock_Guts_MemChain(Mock.SysTick_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void delay_10ms(unsigned long cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_delay_10ms_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_delay_10ms);
  cmock_call_instance = (CMOCK_delay_10ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.delay_10ms_CallInstance);
  Mock.delay_10ms_CallInstance = CMock_Guts_MemNext(Mock.delay_10ms_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_delay_10ms,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_UINT32(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_delay_10ms(CMOCK_delay_10ms_CALL_INSTANCE* cmock_call_instance, unsigned long cmock_arg1);
void CMockExpectParameters_delay_10ms(CMOCK_delay_10ms_CALL_INSTANCE* cmock_call_instance, unsigned long cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void delay_10ms_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned long cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_10ms_CALL_INSTANCE));
  CMOCK_delay_10ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_10ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_10ms_CallInstance = CMock_Guts_MemChain(Mock.delay_10ms_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_delay_10ms(cmock_call_instance, cmock_arg1);
}

void UART0_and_servos_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART0_and_servos_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART0_and_servos_init);
  cmock_call_instance = (CMOCK_UART0_and_servos_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART0_and_servos_init_CallInstance);
  Mock.UART0_and_servos_init_CallInstance = CMock_Guts_MemNext(Mock.UART0_and_servos_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void UART0_and_servos_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART0_and_servos_init_CALL_INSTANCE));
  CMOCK_UART0_and_servos_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART0_and_servos_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART0_and_servos_init_CallInstance = CMock_Guts_MemChain(Mock.UART0_and_servos_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

uint8_t get_UART0_interrupt_data(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_UART0_interrupt_data_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_UART0_interrupt_data);
  cmock_call_instance = (CMOCK_get_UART0_interrupt_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_UART0_interrupt_data_CallInstance);
  Mock.get_UART0_interrupt_data_CallInstance = CMock_Guts_MemNext(Mock.get_UART0_interrupt_data_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void get_UART0_interrupt_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_UART0_interrupt_data_CALL_INSTANCE));
  CMOCK_get_UART0_interrupt_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_UART0_interrupt_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_UART0_interrupt_data_CallInstance = CMock_Guts_MemChain(Mock.get_UART0_interrupt_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_PWM0_generator0_CMPA(unsigned short cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_set_PWM0_generator0_CMPA);
  cmock_call_instance = (CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_PWM0_generator0_CMPA_CallInstance);
  Mock.set_PWM0_generator0_CMPA_CallInstance = CMock_Guts_MemNext(Mock.set_PWM0_generator0_CMPA_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_set_PWM0_generator0_CMPA,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_UINT16(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_set_PWM0_generator0_CMPA(CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE* cmock_call_instance, unsigned short cmock_arg1);
void CMockExpectParameters_set_PWM0_generator0_CMPA(CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE* cmock_call_instance, unsigned short cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void set_PWM0_generator0_CMPA_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned short cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE));
  CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_PWM0_generator0_CMPA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_PWM0_generator0_CMPA_CallInstance = CMock_Guts_MemChain(Mock.set_PWM0_generator0_CMPA_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_set_PWM0_generator0_CMPA(cmock_call_instance, cmock_arg1);
}

void set_PWM0_generator1_CMPA(unsigned short cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_set_PWM0_generator1_CMPA);
  cmock_call_instance = (CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_PWM0_generator1_CMPA_CallInstance);
  Mock.set_PWM0_generator1_CMPA_CallInstance = CMock_Guts_MemNext(Mock.set_PWM0_generator1_CMPA_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_set_PWM0_generator1_CMPA,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_UINT16(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_set_PWM0_generator1_CMPA(CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE* cmock_call_instance, unsigned short cmock_arg1);
void CMockExpectParameters_set_PWM0_generator1_CMPA(CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE* cmock_call_instance, unsigned short cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void set_PWM0_generator1_CMPA_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned short cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE));
  CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_PWM0_generator1_CMPA_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_PWM0_generator1_CMPA_CallInstance = CMock_Guts_MemChain(Mock.set_PWM0_generator1_CMPA_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_set_PWM0_generator1_CMPA(cmock_call_instance, cmock_arg1);
}

